# Generated by Django 2.2.7 on 2019-11-05 17:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="Ex: 'Combien font deux et deux ?'", max_length=100, unique=True)),
                ('content', models.TextField(blank=True, default="Ex: 'Deux et deux font quatre'")),
                ('upload_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('user_approval', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(blank=True, related_name='question', to='faq.Tag')),
            ],
        ),
    ]
