# Generated by Django 2.2.7 on 2019-11-06 13:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'réponse', 'verbose_name_plural': 'réponses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'question'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'mot-clé', 'verbose_name_plural': 'mots-clé'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.AlterField(
            model_name='answer',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='réponse', to='faq.Tag', verbose_name='mots-clé'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(default="Ex: 'Combien font deux et deux ?'", max_length=100, unique=True, verbose_name='question posée'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='upload_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default="Ex: 'Deux et deux font quatre'", verbose_name='réponse apportée'),
        ),
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='question utilisateur'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='mail utilisateur'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='mot'),
        ),
    ]
