# Generated by Django 2.2.7 on 2019-11-23 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_auto_20191120_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_question', models.TextField()),
                ('validated_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.Answer')),
            ],
        ),
    ]
