# Generated by Django 2.2.7 on 2019-11-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_answeredquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_approval',
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
    ]
