# Generated by Django 2.2.7 on 2019-11-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191118_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name="Nom de l'ingrédient"),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='recipetype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='type'),
        ),
    ]
