# Generated by Django 2.2.7 on 2019-11-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20191120_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(null=True, verbose_name='Quantité'),
        ),
    ]
