# Generated by Django 2.2.7 on 2019-11-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20191120_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('F', 'Entrée'), ('M', 'Plat principal'), ('D', 'Dessert')], default='M', max_length=1),
        ),
        migrations.DeleteModel(
            name='RecipeType',
        ),
    ]
