# Generated by Django 2.2.7 on 2019-11-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20191123_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='recipes_pdfs/'),
        ),
    ]
