# Generated by Django 2.2.7 on 2019-11-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité (facultatif)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='recipes_pdfs/', verbose_name='Fichier PDF'),
        ),
    ]
